--- #YAML:1.0
name:               Net-TFTP
version:            0.19
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::MockModule:  0
    Test::More:        0.8701
    Test::Warn:        0
resources:
    repository:  http://github.com/gbarr/perl-net-tftp
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
